# Generated by Django 6.0 on 2026-01-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('online', 'Online Payment')], default='cod', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=0.0, help_text='Contact phone number for delivery', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(default=0.0, help_text='Full shipping address including house number, street, city, state, pin code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total order amount including all items and any fees', max_digits=12),
            preserve_default=False,
        ),
    ]
